###Register User
POST http://localhost:2306/auth/register
Content-Type: application/json

{
  "firstName": "user1",
  "lastName": "test",
  "email": "user1@mail.com",
  "password": "user1234",
  "role": "STUDENT",
  "profileImageUrl":""
}
####Login User
POST http://localhost:2306/auth/login
Content-Type: application/json

{
  "email": "user1@mail.com",
  "password": "user1234"
} 
###Logout User
POST http://localhost:2306/auth/logout
###admin registration
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "firstName": "admin",
  "lastName": "",
  "email": "admin@mail.com",
  "password": "user1234",
  "role": "ADMIN",
  "profileImageUrl":""
}